DROP TRIGGER TRG_SAL;
CREATE TRIGGER TRG_SAL
AFTER UPDATE OR DELETE ON EMP
FOR EACH ROW
DECLARE
	STATUS VARCHAR2(20);
	BEGIN
		IF updating THEN
			STATUS:='UPDATE';
			END IF;
		IF deleting THEN
			STATUS:='DELETE';
			END IF;
		INSERT INTO EMP_AUDIT VALUES(:OLD.EMPNO,:OLD.DEPTNO,STATUS,:OLD.SAL,SYSDATE);
	END;
	/



