SELECT Name FROM CLIENT_MASTER WHERE Name LIKE '_a%';
SELECT Name,City FROM CLIENT_MASTER WHERE City NOT LIKE 'B%';
SELECT Name,City FROM CLIENT_MASTER WHERE LENGTH(Name) = 12 AND Name LIKE 'I%';
SELECT Name,City FROM CLIENT_MASTER WHERE City IN ('Bombay','Delhi');
SELECT * FROM CLIENT_MASTER WHERE Balance_due > 10000;
/*SELECT * FROM SALES_ORDER WHERE Order_date LIKE '%JAN%';*/
SELECT * FROM SALES_ORDER WHERE TO_CHAR(Order_date,'MON') = 'JAN';
SELECT * FROM SALES_ORDER WHERE Client_no IN ('C001','C002');
SELECT * FROM PRODUCT_MASTER WHERE Sell_price BETWEEN 2001 AND 4999;
SELECT * FROM PRODUCT_MASTER WHERE Sell_price > 1500;
SELECT Sell_price,Sell_price * 1.15 NEW_PRICE FROM PRODUCT_MASTER; 
SELECT Name,City,State FROM CLIENT_MASTER WHERE State != 'Maharastra';
SELECT Delivery_date, TO_CHAR(Delivery_date,'Month-DD') FROM SALES_ORDER;
SELECT Order_no,Order_date, TO_CHAR(Order_date,'DD-Month-YY') FROM SALES_ORDER;
SELECT SYSDATE + 15 FROM DUAL;