SET SERVEROUTPUT ON 
DECLARE
    t EXCEPTION;
    PRAGMA
    EXCEPTION_INIT(t,-01400);
BEGIN
    INSERT INTO emp VALUES(null,'X','Y',1234,sysdate,4500,678,30);
EXCEPTION
    WHEN t
    THEN
        dbms_output.put_line('NULL CAN NOT BE ENTERED INTO NOT NULL FIELD.');
END;
/